"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

BRAND_NAME = os.getenv('BRAND_NAME', 'Zorvia Core')
BRAND_COLOR = os.getenv('BRAND_COLOR', 'slate')
CURRENCY_SYMBOL = os.getenv('CURRENCY_SYMBOL', '₹')
BRAND_LOGO = os.getenv('BRAND_LOGO', '/static/default_logo.png')

TAILWIND_COLORS = {
    "slate": {
        "50": "248 250 252", "100": "241 245 249", "200": "226 232 240", "300": "203 213 225",
        "400": "148 163 184", "500": "100 116 139", "600": "71 85 105", "700": "51 65 85",
        "800": "30 41 59", "900": "15 23 42", "950": "2 6 23",
    },
    "indigo": {
        "50": "238 242 255", "100": "224 231 255", "200": "199 210 254", "300": "165 180 252",
        "400": "129 140 248", "500": "99 102 241", "600": "79 70 229", "700": "67 56 202",
        "800": "55 48 163", "900": "49 46 129", "950": "30 27 75",
    },
    "emerald": {
        "50": "236 253 245", "100": "209 250 229", "200": "167 243 208", "300": "110 231 183",
        "400": "52 211 153", "500": "16 185 129", "600": "5 150 105", "700": "4 120 87",
        "800": "6 95 70", "900": "6 78 59", "950": "2 44 34",
    },
    "rose": {
        "50": "255 241 242", "100": "255 228 230", "200": "254 205 211", "300": "253 164 175",
        "400": "251 113 133", "500": "244 63 94", "600": "225 29 72", "700": "190 18 60",
        "800": "159 18 57", "900": "136 19 55", "950": "76 5 25",
    },
    "amber": {
        "50": "255 251 235", "100": "254 243 199", "200": "253 230 138", "300": "252 211 77",
        "400": "251 191 36", "500": "245 158 11", "600": "217 119 6", "700": "180 83 9",
        "800": "146 64 14", "900": "120 53 15", "950": "69 26 3",
    },
    "sky": {
        "50": "240 249 255", "100": "224 242 254", "200": "186 230 253", "300": "125 211 252",
        "400": "56 189 248", "500": "14 165 233", "600": "2 132 199", "700": "3 105 161",
        "800": "7 89 133", "900": "12 74 110", "950": "8 47 73",
    },
}


selected_palette = TAILWIND_COLORS.get(BRAND_COLOR, TAILWIND_COLORS["slate"])
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

DEBUG = os.environ.get('DEBUG', 'False') == 'True'
# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'tracker'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tracker.context_processors.brand_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
                    
UNFOLD = {
    "SITE_TITLE": f"{BRAND_NAME} Portal",
    "SITE_HEADER": f"{BRAND_NAME} Dashboard",  # This fixes the missing space!
    "COLORS": {
        "primary": selected_palette,           # This applies your selected Tailwind color!
    },
    "DASHBOARD_CALLBACK": "tracker.views.admin_dashboard_callback",
    "SITE_ICON": {
        "light": lambda request: BRAND_LOGO,
        "dark": lambda request: BRAND_LOGO,
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Business Tools",
                "separator": True,
                "items": [
                    {"title": "Financial Dashboard", "icon": "monitoring", "link": "/dashboard/"},
                    {"title": "Live Catalogue", "icon": "storefront", "link": "/catalogue/"},
                    {"title": "Barcode Scanner", "icon": "qr_code_scanner", "link": "/scanner/"},
                ],
            },
        ],
    },
}