# Generated by Django 6.1 on 2026-08-12 17:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(help_text='e.g., SUIT, SAREE, GHARARA', max_length=50)),
                ('design_work', models.CharField(blank=True, help_text='e.g., JANGAL KADWA', max_length=100, null=True)),
                ('weaver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('DISPATCHED', 'Dispatched'), ('RETURNED', 'Returned')], default='IN_STOCK', max_length=20)),
                ('date_entered', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_dispatched', models.DateTimeField(blank=True, null=True)),
                ('sales_channel', models.CharField(blank=True, choices=[('RETAIL', 'Retail Shop'), ('WHOLESALE', 'Wholesale B2B'), ('ONLINE', 'Online E-commerce')], max_length=20, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('derived_state', models.CharField(blank=True, max_length=50, null=True)),
                ('derived_city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
