# Generated by Django 6.1 on 2026-08-15 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='derived_city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='derived_state',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='design_work',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='product_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='weaver_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
