# Generated by Django 6.1 on 2026-09-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_finishedproduct_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_name', models.CharField(help_text='Name of the reseller company', max_length=100)),
                ('token', models.CharField(blank=True, help_text='Auto-generated secure access token', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to instantly revoke access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price of the item', max_digits=10),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('UNSOLD', 'Unsold / Stock Swap'), ('DEFECTIVE', 'Defective / Damaged'), ('CANCELED', 'Customer Canceled'), ('WRONG_ITEM', 'Wrong Item Shipped'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
