# Generated by Django 6.1 on 2026-09-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_catch_up_price_return_reseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Textiler', max_length=100)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('accent_hex', models.CharField(default='#C8A46E', help_text='Primary brand color as a hex code, e.g. #C8A46E', max_length=7)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('is_setup_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='dead_stock_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='is_dead_stock',
            field=models.BooleanField(db_index=True, default=False, help_text='Slow-moving stock flagged for clearance. Still counts as available inventory.'),
        ),
    ]
